#!bin/bash

for i in data/intermediate/str_shared*
do
d=$(echo $i | sed 's/^.*str_/data\/final\/run_/1')
mkdir $d
~/.local/bin/structure_threader run -K 8 -R 10 \
-i $i/*.str \
-o $d \
-t 8 \
-st ~/.local/bin/structure \
--log 1 \
--params $i/mainparams
done
